#!/bin/bash

if [ $# -lt 1 ]; then
	echo $0 file.img
	exit 1
fi

if [ -z "$TMPDIR" ]; then
	TMPDIR=/tmp
fi

SCR=$TMPDIR/qemu.$RANDOM
rm -f $SCR

FILE=$1
shift

qemu-kvm -k en-us -usbdevice tablet -hda $FILE -smp 2 -m 1000 -net user -net nic,model=e1000 -usb -serial pty "$@" 2>$SCR &
QEMU=$!

while ! grep -q 'redirected to' $SCR; do
	usleep 100000
done

screen `sed -ne '/redirected to / s/.* // p' $SCR`

rm -f $SCR

wait $QEMU
