#!/bin/sh

HOST=$1.suse.de
if ! host $HOST >/dev/null; then
	HOST=$1.arch.suse.de
fi
if ! host $HOST >/dev/null; then
	HOST=$1.suse.cz
fi

if ! ping -c 1 $HOST -W 2 -q >/dev/null; then
	echo $HOST is DEAD
	exit 0
fi

CMD="ssh -CX jslaby@$HOST"
echo $CMD
$CMD
