alias sa='ssh aisa -CX'
alias sb="ssh bellona -CX"
alias sd='ssh decibel -CX'
alias san='ssh anemoi -X'

alias osci='osc -A https://api.suse.de'
alias oscp='osc -A https://pmbs-api.links2linux.org'
alias oscss='osc service remoterun home:jirislaby slaby-scripts'

alias gde='git describe --contains --exact-match'
alias gpr='git pull --rebase'
alias gru='git remote update'

alias tigl='tig -1000'
alias tign='tig korg/next_master..'
alias tigs='tig v3.12..'

alias cdl='cd ~/linux'
alias cds='cd ~/tmp/stable-3.12'
alias cdsl='cd ~/repos/slaby-scripts/'
alias cdsu='cd ~/repos/suse/kernel-source/'
alias cdq='cd ~/repos/stable-queue/queue-3.14/'
alias cdx='cd ~/repos/xf86-video-intel/'
alias cdk='cd ~/kernel-source'

function stable_dry() {
	patch --dry-run -p1 -i ~/repos/stable-queue/queue-3.14/"$1"
}
