HISTSIZE=10000
LESS="-M -R -X -F -i"

if less --help|grep -q -- --mouse; then
	LESS="$LESS --mouse --wheel-lines=3"
fi

if [ -d "/opt/cross/" ]; then
	for C in /opt/cross/gcc*/*/bin/; do
		PATH="$PATH:$C"
	done
fi

if [ -d "/dev/shm/jslaby" -a -x /usr/bin/ccache ]; then
	export CCACHE_MAXSIZE=20G
	export CCACHE_DIR=/dev/shm/jslaby/ccache
fi
