HISTSIZE=10000
LESS="-M -R -X -F -i"

if less --help|grep -q -- --mouse; then
	LESS="$LESS --mouse --wheel-lines=3"
fi

if [ -d "/opt/cross/" ]; then
	for C in /opt/cross/*/bin/; do
		PATH=$PATH:$C
	done
fi

if [ -d "/dev/shm/jslaby" -a -x /usr/bin/ccache ]; then
	CCACHE_MAXSIZE=20G
	CCACHE_DIR=/dev/shm/jslaby/ccache
fi
