alias sa='ssh aisa -CX'
alias sb="ssh bellona -CX"
alias sd='ssh decibel -CX'
alias san='ssh anemoi -X'

alias osci='osc -A https://api.suse.de'
alias oscp='osc -A https://pmbs-api.links2linux.org'

alias tign='tig korg/next_master..'
alias tigl='tig -1000'

function stable_rm() {
	for file in $@; do
		git rm "$file"
		grep -v "^$file$" series > series1
		mv series1 series
	done
}
